### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by LiteSun** [gdut-yy/CSS-The-Definitive-Guide-4th-zh#10]
有些词语翻译的不太准确
![image](https://user-images.githubusercontent.com/31329157/80365025-86cb0200-88b9-11ea-93bf-4195b47706ff.png)

下图推测是打错了，应该是`:`而错误打成了 L
![image](https://user-images.githubusercontent.com/31329157/80365066-98aca500-88b9-11ea-83e8-dde08754ca87.png)

**Comment by gdut-yy** [comment]
fixed by eb809b8e1c7dfcb92b7c164c37e074372fbe2e6d
