### ISSUE TITLE
Figure的图像本地预览不会显示

### ISSUE THREAD

**Issue by Stone-ChenLijun** [gdut-yy/CSS-The-Definitive-Guide-4th-zh#12]
我fork了仓库，在本地预览，但是figure标签指定的图片并没有显示。

下面是线上预览的截图：
![online](https://user-images.githubusercontent.com/22467090/84470630-53e89c00-acb6-11ea-9e5f-59e7c127d34f.png)

下面是我本地预览的截图，红色框是本来应该出现图片的位置：
![local](https://user-images.githubusercontent.com/22467090/84470718-80041d00-acb6-11ea-8f62-1e9012527ff8.png)

**Comment by Stone-ChenLijun** [comment]
我在windows环境下能支持显示图片，但是在linux环境下，就无法显示环境，我的linux 是 manjaro 20.02

**Comment by gdut-yy** [comment]
@Stone-ChenLijun 本项目还未在linux环境下进行测试，图片这块是一个 Vue 组件。可以用浏览器的开发者模式调试一下，也可能跟目标浏览器有关

**Comment by Stone-ChenLijun** [comment]
解决了，我的锅，用yarn install的时候，因为本地没有配置NODE_ENV，使得yarn认为当前环境为production，所以没有安装package.json dependencies里的依赖。可以通过配置NODE_ENV=development，或使用yarn install --production=false使其安装dependencies。
