### ISSUE TITLE
figure error

### ISSUE THREAD

**Issue by brightzoe** [gdut-yy/CSS-The-Definitive-Guide-4th-zh#2]
你好，请检查一下ch12的图21-26，图片命名有点问题(･ω･ ) 

[gitee位置](http://gdut_yy.gitee.io/gitee-page/ch12.html#_12-5-justifying-content)
[图片地址](https://github.com/gdut-yy/CSS-The-Definitive-Guide-4th-zh/tree/master/docs/.vuepress/public/figures/ch12)

ps:后面是还没来得及翻译吗？我有兴趣加入翻译，不知道是否可以？
每天大概可以抽出半个小时到一个小时时间，不过我还是一个css初学者。

**Comment by Tomatoro** [comment]
Hello, I'm glad to see such an excellent article, and I'll be happy to join you in order to contribute more developers.Thanks!

**Comment by gdut-yy** [comment]
> Hello, I'm glad to see such an excellent article, and I'll be happy to join you in order to contribute more developers.Thanks!

Welcome!~

**Comment by gdut-yy** [comment]
> 你好，请检查一下ch12的图21-26，图片命名有点问题(･ω･ )
> 
> [gitee位置](http://gdut_yy.gitee.io/gitee-page/ch12.html#_12-5-justifying-content)
> [图片地址](https://github.com/gdut-yy/CSS-The-Definitive-Guide-4th-zh/tree/master/docs/.vuepress/public/figures/ch12)
> 
> ps:后面是还没来得及翻译吗？我有兴趣加入翻译，不知道是否可以？
> 每天大概可以抽出半个小时到一个小时时间，不过我还是一个css初学者。

平时工作较忙，非常期待你的加入！~

**Comment by gdut-yy** [comment]
该issue已被修复
