### ISSUE TITLE
2.6.2 结构性伪类中的选择空元素

### ISSUE THREAD

**Issue by growYdp** [gdut-yy/CSS-The-Definitive-Guide-4th-zh#9]
```
<p></p>
<p></p>
<p></p>
<p><!—-a comment--></p>
```
*但是上下文的描述是：*
1.（上文）注意，一个元素如果要被:empty匹配，它必须（从解析的角度看）是真正空的——没有空白、可见内容，或后代元素。在下面的元素中，只有第一个和最后一个会被p:empty匹配。
2. （下文）第二个和第三个段落不会匹配:empty，因为它们不是空的：它们各自包含一个空格和一个换行符，都会被当做文本节点，因此不是空状态。

**但是代码中第二第三段落并没有空格和换行符。**

**Comment by nick950222** [comment]
这个估计是放上来的时候没转义吧

**Comment by gdut-yy** [comment]
@gdut-wj 你的 bug 诶

**Comment by gdut-yy** [comment]
fixed by 1484841f9027284442351906c3fb29813c66fddd
